image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: open-preview

tasks:
  - init: make up

vscode:
  extensions:
    - felixfbecker.php-debug
    - bmewburn.vscode-intelephense-client